spring.application.name=microUsuarios
server.port=5000
# ===============================
#   BASE DE DATOS PostgreSQL (Neon)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-old-glitter-ahsakfph-pooler.c-3.us-east-1.aws.neon.tech:5432/usuariosDB?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CdA2Ueg8tfOo


# ===============================
#   JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
#   DEBUG
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
#   Auth0
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-q8voma4k1vi0ux1s.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://BarbaNegra.com

# ===============================
#   LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.co.edu.unicauca.microUsuarios=DEBUG